version: 2
jobs:
  build:
    working_directory: /src/app
    docker:
      - image: node:9.9
    steps:
      - checkout
      - run:
          name: Install NPM dependencies
          command: yarn install
      - run:
          name: build
          command: yarn run build
      - run:
          name: Run ESLint
          command: yarn run lint
      - run:
          name: Run tests
          command: yarn run test
      - store_test_results:
          path: reports
      - deploy:
          name: Publish NPM release
          command: yarn run semantic-release
